#
# ~/.zshrc
#

# Source modular config files
for config_file in ~/.zsh/{config,env,aliases,completion}.zsh; do
  [[ -f "$config_file" ]] && source "$config_file"
done

# Oh My Zsh
ZSH_THEME="adambware"
export UPDATE_ZSH_DAYS=7
COMPLETION_WAITING_DOTS="true"
plugins=(git macos brew)
export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Private env (gitignored)
[[ -f ~/.zsh/env.local.zsh ]] && source ~/.zsh/env.local.zsh
