#
# ~/.zshrc
#
# All config (aliases, env, completion, theme, plugins) lives in
# ~/.oh-my-zsh/custom/ via https://github.com/adambware/omz-custom
# Oh My Zsh auto-sources all *.zsh files in that directory.
#

export ZSH=~/.oh-my-zsh

# ohmyzsh.zsh in custom/ sets ZSH_THEME, plugins, etc.
# Source it early so those vars are set before oh-my-zsh.sh runs.
[[ -f "$ZSH/custom/ohmyzsh.zsh" ]] && source "$ZSH/custom/ohmyzsh.zsh"

source $ZSH/oh-my-zsh.sh
