---
# tasks file for adambware.auto-updates

- name: Configure macOS automatic updates
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop:
    # Enable automatic update check
    - { domain: "com.apple.SoftwareUpdate", key: "AutomaticCheckEnabled", type: "bool", value: true }
    # Check for updates daily
    - { domain: "com.apple.SoftwareUpdate", key: "ScheduleFrequency", type: "int", value: 1 }
    # Download updates in background
    - { domain: "com.apple.SoftwareUpdate", key: "AutomaticDownload", type: "bool", value: true }
    # Install app updates automatically
    - { domain: "com.apple.commerce", key: "AutoUpdate", type: "bool", value: true }
    # Install macOS updates automatically
    - { domain: "com.apple.SoftwareUpdate", key: "AutomaticallyInstallMacOSUpdates", type: "bool", value: "{{ auto_install_macos_updates }}" }
    # Install security updates automatically
    - { domain: "com.apple.SoftwareUpdate", key: "CriticalUpdateInstall", type: "bool", value: true }
  when: enable_auto_updates | default(true)
