---
galaxy_info:
  author: Adam Boulware
  description: Set up Ruby environment via rbenv
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: macOS
      versions:
        - all

dependencies: []
  
