---
# tasks file for adambware.zsh

- name: Checking default shell
  ansible.builtin.shell: dscl . -read /Users/{{ main_username }} UserShell | awk '{print $2}'
  register: default_shell
  changed_when: false

- name: Ensure brew'd zsh added to /etc/shells
  ansible.builtin.lineinfile:
    dest: /etc/shells
    line: "{{ zsh_path }}"
    state: present
  become: yes
  when: default_shell.stdout != zsh_path

- name: Ensure brew'd zsh set as default shell
  ansible.builtin.user:
    name: "{{ main_username }}"
    shell: "{{ zsh_path }}"
  become: yes
  when: default_shell.stdout != zsh_path

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: oh_my_zsh_check

- name: Ensure oh-my-zsh is installed
  ansible.builtin.shell: sh -c "$(curl -fsSL {{ oh_my_zsh_install_url }})" "" --unattended
  when: not oh_my_zsh_check.stat.exists

- name: Create custom directory for Oh My Zsh
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom"
    state: directory
    mode: '0755'

- name: Create themes directory for Oh My Zsh
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes"
    state: directory
    mode: '0755'

- name: Deploy zsh config
  ansible.builtin.copy:
    src: config.zsh.in
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/config.zsh"
    owner: "{{ main_username }}"
    mode: '0644'

- name: Deploy oh-my-zsh config
  ansible.builtin.copy:
    src: ohmyzsh.zsh.in
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/ohmyzsh.zsh"
    owner: "{{ main_username }}"
    mode: '0644'

- name: Deploy aliases
  ansible.builtin.copy:
    src: aliases.zsh.in
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/aliases.zsh"
    owner: "{{ main_username }}"
    mode: '0644'

- name: Deploy environment vars
  ansible.builtin.copy:
    src: env.zsh.in
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/env.zsh"
    owner: "{{ main_username }}"
    mode: '0644'

- name: Deploy completions
  ansible.builtin.copy:
    src: completion.zsh.in
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/completion.zsh"
    owner: "{{ main_username }}"
    mode: '0644'

- name: Deploy adambware.zsh-theme
  ansible.builtin.copy:
    src: adambware.zsh-theme.in
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/adambware.zsh-theme"
    owner: "{{ main_username }}"
    mode: '0644'
