---
# meta file for adambware.test
galaxy_info:
  author: Adam Boulware
  description: Run tests to validate macOS setup
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: macOS
      versions:
        - all

dependencies: []
