---
# tasks file for adambware.ruby

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: not ansible_check_mode

- name: Install rbenv and ruby-build
  community.general.homebrew:
    name: 
      - rbenv
      - ruby-build
    state: present

- name: Determine rbenv root path
  ansible.builtin.set_fact:
    rbenv_root: "{{ ansible_env.HOME }}/.rbenv"

- name: Set up rbenv in shell config
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} RBENV CONFIGURATION"
    block: |
      export RBENV_ROOT="{{ rbenv_root }}"
      eval "$(rbenv init -)"
    create: yes

- name: Check if Ruby version is installed
  ansible.builtin.shell: >
    export RBENV_ROOT="{{ rbenv_root }}" && 
    eval "$(rbenv init -)" && 
    rbenv versions | grep {{ ruby_version }}
  args:
    executable: /bin/zsh
  register: ruby_installed
  changed_when: false
  failed_when: false

- name: Install Ruby
  ansible.builtin.shell: >
    export RBENV_ROOT="{{ rbenv_root }}" && 
    eval "$(rbenv init -)" && 
    rbenv install -s {{ ruby_version }}
  args:
    executable: /bin/zsh
  when: ruby_installed.rc != 0 and not ansible_check_mode

- name: Set global Ruby version
  ansible.builtin.shell: >
    export RBENV_ROOT="{{ rbenv_root }}" && 
    eval "$(rbenv init -)" && 
    rbenv global {{ ruby_version }}
  args:
    executable: /bin/zsh
  when: not ansible_check_mode

- name: Update to latest rubygems version
  ansible.builtin.shell: >
    export RBENV_ROOT="{{ rbenv_root }}" && 
    eval "$(rbenv init -)" && 
    gem update --system
  args:
    executable: /bin/zsh
  register: gem_update
  changed_when: "'Latest version already installed' not in gem_update.stdout"
  when: not ansible_check_mode

- name: Check if Ruby gems are installed
  ansible.builtin.shell: >
    export RBENV_ROOT="{{ rbenv_root }}" && 
    eval "$(rbenv init -)" && 
    gem list | grep -i "{{ item }}"
  args:
    executable: /bin/zsh
  register: ruby_gems_check
  changed_when: false
  failed_when: false
  with_items: "{{ ruby_gems }}"

- name: Install common Ruby gems
  ansible.builtin.shell: >
    export RBENV_ROOT="{{ rbenv_root }}" && 
    eval "$(rbenv init -)" && 
    gem install {{ item.item }}
  args:
    executable: /bin/zsh
  with_items: "{{ ruby_gems_check.results }}"
  when: item.rc != 0 and not ansible_check_mode
