---
# tasks file for adambware.python
  - name: Ensure Homebrew is installed
    shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      creates=/usr/local/bin/brew

  - name: Update Homebrew
    homebrew:
      update_homebrew=yes

  - name: Ensure pyenv is installed
    homebrew:
      name=pyenv
      state=latest

  - name: Init pyenv for zsh or bash
    shell: if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi

  - name: Install python
    shell: pyenv install "{{ python_version }}"
      creates={{ pyenv_root }}/versions/{{ python_version }}

  - name: Set installed python as global default
    shell: pyenv global "{{ python_version }}";
