---
# tasks file for adambware.node

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: not ansible_check_mode

- name: Install node.js via Homebrew
  community.general.homebrew:
    name: node
    state: present

- name: Check if NVM is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_check

- name: Install nvm (Node Version Manager)
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: not nvm_check.stat.exists and not ansible_check_mode
  
- name: Set up NVM in shell config
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} NVM CONFIGURATION"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    create: yes

- name: Install Node LTS version
  ansible.builtin.shell: >
    source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_lts_version }}
  args:
    executable: /bin/bash
  register: nvm_install
  changed_when: "'is already installed' not in nvm_install.stdout"
  when: not ansible_check_mode
    
- name: Check if global npm packages are installed
  ansible.builtin.shell: npm list -g --depth=0 | grep "{{ item }}"
  args:
    executable: /bin/bash
  register: npm_packages_check
  changed_when: false
  failed_when: false
  with_items: "{{ npm_global_packages }}"
    
- name: Install global npm packages
  community.general.npm:
    name: "{{ item.item }}"
    global: yes
  with_items: "{{ npm_packages_check.results }}"
  when: item.rc != 0 and not ansible_check_mode
