---
# Safari settings and security preferences

- name: Set Safari preferences
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  loop:
    # Set Safari's home page to about:blank for faster loading
    - { domain: "com.apple.Safari", key: "HomePage", type: "string", value: "about:blank" }
    # Prevent Safari from opening 'safe' files automatically after downloading
    - { domain: "com.apple.Safari", key: "AutoOpenSafeDownloads", type: "bool", value: false }
    # Enable Safari's debug menu
    - { domain: "com.apple.Safari", key: "IncludeInternalDebugMenu", type: "bool", value: true }
    # Enable the Develop menu and the Web Inspector in Safari
    - { domain: "com.apple.Safari", key: "IncludeDevelopMenu", type: "bool", value: "{{ safari_enable_developer_menu }}" }
    - { domain: "com.apple.Safari", key: "WebKitDeveloperExtrasEnabledPreferenceKey", type: "bool", value: "{{ safari_enable_developer_menu }}" }
    - { domain: "com.apple.Safari", key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled", type: "bool", value: "{{ safari_enable_developer_menu }}" }
    # Show the full URL in the address bar
    - { domain: "com.apple.Safari", key: "ShowFullURLInSmartSearchField", type: "bool", value: "{{ safari_show_full_url }}" }
    # Disable autofill
    - { domain: "com.apple.Safari", key: "AutoFillFromAddressBook", type: "bool", value: "{{ safari_autofill_contacts | default(false) }}" }
    - { domain: "com.apple.Safari", key: "AutoFillPasswords", type: "bool", value: "{{ safari_autofill_passwords | default(false) }}" }
    - { domain: "com.apple.Safari", key: "AutoFillCreditCardData", type: "bool", value: "{{ safari_autofill_credit_cards | default(false) }}" }
    - { domain: "com.apple.Safari", key: "AutoFillMiscellaneousForms", type: "bool", value: "{{ safari_autofill_other_forms | default(false) }}" }
  when: configure_safari | default(true)
