---
# defaults file for adambware.auto-updates

# Set to true to enable automatic updates
enable_auto_updates: true

# Set to true to auto-install macOS updates (restarts may occur)
auto_install_macos_updates: false
