---
# defaults file for adambware.auto-updates

# Set to true to enable automatic security updates
enable_auto_updates: true

# Set to true to auto-install all macOS updates (restarts may occur)
auto_install_macos_updates: false
