---
# defaults file for adambware.osx

# General UI
enable_dark_mode: true

# Input device settings
configure_input_devices: true
configure_trackpad: true
keyboard_auto_capitalize: false
keyboard_auto_smart_dashes: false
keyboard_auto_smart_periods: false
keyboard_auto_smart_quotes: false
trackpad_tap_to_click: true
trackpad_right_click: true
trackpad_corner_secondary_click: 0

# Screen settings
screenshot_location: "{{ ansible_env.HOME }}/Desktop"
screenshot_format: "png"
screenshot_disable_shadow: true
require_password_after_sleep: true
password_delay_seconds: 0

# Finder settings
show_hidden_files: true
show_file_extensions: true
show_path_in_title_bar: true
show_status_bar: true
finder_default_view: "Nlsv"  # List view (other options: icnv, clmv, Flwv)

# Dock settings
dock_position: "right"  # Options: left, bottom, right
dock_auto_hide: true
dock_magnification: false
dock_minimize_effect: "genie"  # Options: genie, scale, suck
dock_show_only_active: false

# Safari settings
configure_safari: true
safari_show_full_url: true
safari_enable_developer_menu: true
safari_autofill_contacts: false
safari_autofill_passwords: false
safari_autofill_credit_cards: false
safari_autofill_other_forms: false

# Security settings
enable_filevault: false
enable_firewall: true
disable_remote_login: true
