---
# tasks file for adambware.homebrew-casks

- name: Check Homebrew status
  ansible.builtin.command: brew outdated
  register: homebrew_status
  changed_when: false
  failed_when: false

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: homebrew_status.stdout != "" and not ansible_check_mode

- name: Ensure casks are installed
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=/Applications"
  with_items: "{{ casks }}"
