---
# tasks file for adambware.homebrew-casks

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Ensure casks are installed
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=/Applications"
  with_items: "{{ casks }}"
